name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    env:
      repository: scylladb/scylla
      working-directory: ${{ github.workspace }}/src/github.com/scylladb/scylla
      GOPATH: ${{ github.workspace }}
    runs-on: ubuntu-18.04
    steps:
      # Does this change the working directory
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: src/github.com/${{ env.repository }}
  
      - name: Install python3 deps
        run: pip3 install requests
  
      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v1
        with:
          path: bin/deps
          # format('{0}{1}', github.workspace, '/mix.lock')
          key: ${{ runner.os }}-${{ hashFiles(format('src/github.com/{0}/hack/binary_deps.py', env.repository)) }}
  
      - name: Install tools
        if: steps['cache-tools'].outputs['cache-hit'] != 'true'
        working-directory: ${{ env.working-directory }}
        run: make bin/deps
  
      - name: Build
        working-directory: ${{ env.working-directory }}
        run: make local-build

# vendor - add deps
# fmt
# vet
# generate code
# unit tests
# docker build
# docker push
