name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    env:
      GOPATH: ${{ github.workspace }}
    runs-on: ubuntu-18.04
    steps:
      # Does this change the working directory
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: src/github.com/${{ github.repository }}
  
      - name: Install python3 deps
        run: pip3 install requests
  
      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v1
        with:
          path: bin/deps
          key: ${{ runner.os }}-${{ hashFiles('hack/binary_deps.py') }}
  
      - name: Install tools
        if: steps['cache-tools'].outputs['cache-hit'] != 'true'
        working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
        run: make bin/deps
  
      - name: Build
        working-directory: ${{ github.workspace }}/src/github.com/${{ github.repository }}
        run: make local-build

# vendor - add deps
# fmt
# vet
# generate code
# unit tests
# docker build
# docker push
